# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{csvscan-enphase}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Cranston"]
  s.date = %q{2011-10-12}
  s.description = %q{This is a packaged version of CSVScan, written by MoonWolf. If you can read Japanese, checkout README.ja for whatever he said.

On a 10,000 line file:

    time cat example.csv | ruby fastercsv_benchmark.rb

    real	0m8.804s
    user	0m8.502s
    sys	0m0.304s

    time cat example.csv | ruby csvscan_benchmark.rb 

    real	0m0.860s
    user	0m0.782s
    sys	0m0.088s}
  s.email = %q{ecranston@enphaseenergy.com}
  s.extensions = ["ext/csvscan/extconf.rb"]
  s.extra_rdoc_files = [
    "README.ja",
    "README.txt"
  ]
  s.files = [
    "History.txt",
    "Manifest.txt",
    "README.ja",
    "README.txt",
    "Rakefile",
    "csvscan.gemspec",
    "ext/csvscan/MANIFEST",
    "ext/csvscan/csvscan.c",
    "ext/csvscan/csvscan.rl",
    "ext/csvscan/extconf.rb",
    "setup.rb",
    "test/test_csvscan.rb"
  ]
  s.homepage = %q{http://github.com/cracell/csvscan}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{This is a packaged version of CSVScan, written by MoonWolf}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

